//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVX.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncio()
        {
            this.Foto = new HashSet<Foto>();
        }
        [DataType(DataType.Upload)]
        [Display(Name = "Subir Archivo")]
        public HttpPostedFileBase[] files { get; set; }
        public string idAnuncio { get; set; }
        public string titulo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string modelo { get; set; }
        public string marca { get; set; }
        public int idCategoria { get; set; }
        public int idUsuario { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> disponible { get; set; }
        public decimal latitud { get; set; }
        public decimal longitud { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public int estadoProducto { get; set; }
        public Nullable<int> estado { get; set; }

        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto> Foto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}

