//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anuncio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anuncio()
        {
            this.Foto = new HashSet<Foto>();
        }
    
        public int idAnuncio { get; set; }
        public string titulo { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string estado { get; set; }
        public int latitud { get; set; }
        public int longitud { get; set; }
        public string disponible { get; set; }
        public int idCategoria { get; set; }
        public int idUsuario { get; set; }
        public double precio { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Foto> Foto { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
